public enum StatusEffectType
{
    None,
    Limping,
    Dizziness,
    BloodLoss,
    Infection,
    Hypothermia,
    Heatstroke,
    Poisoned,
    Blinded,
    Exhausted,
    Stressed,
    Pestilence,
    Starving,
    DimensionalShift,
    Infatuation,
    Foreboding,
    Consumed,
    TemporalDisplacement,
    Frustration,
    InterdimensionalConnection,
    UnintendedConsequences
}